// Code generated by mockery v2.49.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Feride3d/backup-creator/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// Backuper is an autogenerated mock type for the Backuper type
type Backuper struct {
	mock.Mock
}

// SaveContent provides a mock function with given fields: ctx, blocks, folder
func (_m *Backuper) SaveContent(ctx context.Context, blocks []model.ContentBlock, folder string) error {
	ret := _m.Called(ctx, blocks, folder)

	if len(ret) == 0 {
		panic("no return value specified for SaveContent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []model.ContentBlock, string) error); ok {
		r0 = rf(ctx, blocks, folder)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBackuper creates a new instance of Backuper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBackuper(t interface {
	mock.TestingT
	Cleanup(func())
}) *Backuper {
	mock := &Backuper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
